---
rnd: 7385
resourcegroup: "mlops-quickstart-$rnd"
location: "westeurope"
workspace: "mlops-myworkspace"
project: "mlops-quickstart-$rnd"
repository: "mlops-repo-$rnd"
organization: "mlops-template"
orguri: "https://dev.azure.com/$organization/"
serviceconnection: "mlops-sc"
variablegroup: "vargroup"
experiment: "mlops-experiment"
compute: "aml-compute-$rnd"
model_name: "compliance-classifier"
image_name: "compliance-classifier-image"
AZURE_DEVOPS_EXT_PAT: 6wonqckz5hrmaoqgxcd3bs2gu6mjguahepmdzaf7y7ksk64hfg4a
datastorage: "mlops-data-$rnd"
